print("Nama : Ariza Malik Ismail")
print("NIM : 312110299")
print("Kelas : TI.21.A.1")
print("=======================")
print()

kontak = {"Acung": "085215565501", "Lala": "08788767778"}
print("Nama | Nomor Telepon")
print("Menampilkan Dictionary Kontak")
print(kontak)
print("----------------------------------------------")
print("Menampilkan Kontak Acung")
print(kontak['Acung'])
print("----------------------------------------------")
print("Menambahkan kontak baru dengan nama Riko - 087654544")
kontak['Riko'] = '087654544'
print(kontak['Riko'])
print("----------------------------------------------")
print("Ubah kontak Lala dengan nomor baru 088999776")
kontak['Lala'] = '088999776'
print(kontak['Lala'])
print("----------------------------------------------")
print("Tampilkan semua Nama")
print(kontak.keys())
print("----------------------------------------------")
print("Tampilkan semua Nomor")
print(kontak.values())
print("----------------------------------------------")
print("Tampilkan daftar nama dan nomor")
print(kontak.items())
print("----------------------------------------------")
print("Hapus kontak Lala")
del kontak['Lala']
print(kontak)